# Generated from feed.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "init_files=false".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


_FruitFields: TypeAlias = Literal["time", "edition", "content", "guid", "sign"]

class Fruit(Message[_FruitFields]):
    """
    A single feed entry — one fruit the sclerotium bears.

    ```proto
    message Mycelium.v1.Fruit
    ```

    Attributes:
        time:
            ```proto
            bytes time = 1;
            ```
        edition:
            ```proto
            bytes edition = 2;
            ```
        content:
            ```proto
            bytes content = 3;
            ```
        guid:
            ```proto
            bytes guid = 4;
            ```
        sign:
            ```proto
            bytes sign = 5;
            ```
    """

    __slots__ = ("time", "edition", "content", "guid", "sign")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            time: bytes = b"",
            edition: bytes = b"",
            content: bytes = b"",
            guid: bytes = b"",
            sign: bytes = b"",
        ) -> None:
            pass

        time: bytes
        edition: bytes
        content: bytes
        guid: bytes
        sign: bytes

_SclerotiumFields: TypeAlias = Literal["time", "edition", "content", "sign", "fruits"]

class Sclerotium(Message[_SclerotiumFields]):
    """
    The feed message — the sclerotium: metadata plus the fruits it bears.

    ```proto
    message Mycelium.v1.Sclerotium
    ```

    Attributes:
        time:
            ```proto
            bytes time = 1;
            ```
        edition:
            ```proto
            bytes edition = 2;
            ```
        content:
            ```proto
            bytes content = 3;
            ```
        sign:
            ```proto
            bytes sign = 4;
            ```
        fruits:
            ```proto
            repeated Mycelium.v1.Fruit fruits = 5;
            ```
    """

    __slots__ = ("time", "edition", "content", "sign", "fruits")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            time: bytes = b"",
            edition: bytes = b"",
            content: bytes = b"",
            sign: bytes = b"",
            fruits: list[Fruit] | None = None,
        ) -> None:
            pass

        time: bytes
        edition: bytes
        content: bytes
        sign: bytes
        fruits: list[Fruit]


_DESC = file_desc(
    b'\n\nfeed.proto\x12\x0bMycelium.v1"w\n\x05Fruit\x12\x12\n\x04time\x18\x01 \x01(\x0cR\x04time\x12\x18\n\x07edition\x18\x02 \x01(\x0cR\x07edition\x12\x18\n\x07content\x18\x03 \x01(\x0cR\x07content\x12\x12\n\x04guid\x18\x04 \x01(\x0cR\x04guid\x12\x12\n\x04sign\x18\x05 \x01(\x0cR\x04sign"\x94\x01\n\nSclerotium\x12\x12\n\x04time\x18\x01 \x01(\x0cR\x04time\x12\x18\n\x07edition\x18\x02 \x01(\x0cR\x07edition\x12\x18\n\x07content\x18\x03 \x01(\x0cR\x07content\x12\x12\n\x04sign\x18\x04 \x01(\x0cR\x04sign\x12*\n\x06fruits\x18\x05 \x03(\x0b2\x12.Mycelium.v1.FruitR\x06fruitsb\x06proto3',
    [],
    {
        "Fruit": Fruit,
        "Sclerotium": Sclerotium,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `feed.proto`."""
    return _DESC
